# This workflow will build the release jar using Maven and then attach it on to the release
# uses https://github.com/actions/setup-java/ as it's base

name: Jar on Release

on:
  release:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
          mvn -X -e -B package --file pom.xml
          gh release upload ${{github.event.release.tag_name}} target/user-agent-valve-${{github.event.release.tag_name}}.jar
      env:
        GITHUB_TOKEN: ${{ github.token }}
